apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana-kibana
  namespace: logging
spec:
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
    nodePort: 31814
  selector:
    app: kibana
  type: NodePort
