apiVersion: v1
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      if [kubernetes][labels][log] == "v1" {
        grok {
          match => { "message" => "%{TIMESTAMP_ISO8601:log_time}\|%{NOTVLINE:log_level}\|%{NOTVLINE:log_app}\|%{NOTVLINE:log_pid}\|%{NOTVLINE:log_thread}\|%{NOTVLINE:log_class}\|%{GREEDYDATA:log_message}"}
        }
      }
    }
    output {
      if [kubernetes][labels][log] == "v1" {
        elasticsearch {
          hosts => ["elasticsearch-master:9200"]
          index => "kubernetes-app-%{+YYYY.MM.dd}"
          user => "elastic"
          password => "123"
        }
       } else {
          elasticsearch {
          hosts => ["elasticsearch-master:9200"]
          index => "kubernetes-soft-%{+YYYY.MM.dd}"
          user => "elastic"
          password => "123"
          }
        }                      
     }
kind: ConfigMap
metadata:
  labels:
    app: logstash-logstash
  name: logstash-logstash-pipeline
  namespace: logging

