apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: logstash-logstash
  name: logstash-logstash
  namespace: logging
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: logstash-logstash
  serviceName: logstash-logstash-headless
  template:
    metadata:
      labels:
        app: logstash-logstash
      name: logstash-logstash
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - logstash-logstash
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: LS_JAVA_OPTS
          value: -Xmx1g -Xms1g
        image: harbor-k8s.iwgame.com/containers/logstash:7.6.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: logstash
        ports:
        - containerPort: 9600
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1536Mi
          requests:
            cpu: 100m
            memory: 1536Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/logstash/config/logstash.yml
          name: logstashconfig
          subPath: logstash.yml
        - mountPath: /usr/share/logstash/pipeline/logstash.conf
          name: logstashpipeline
          subPath: logstash.conf
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: logstash-logstash-config
        name: logstashconfig
      - configMap:
          defaultMode: 420
          name: logstash-logstash-pipeline
        name: logstashpipeline
  updateStrategy:
    type: RollingUpdate

