apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash-logstash
  name: logstash-logstash
  namespace: logging
spec:
  ports:
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: 5044
  selector:
    app: logstash-logstash
  sessionAffinity: None
  type: ClusterIP
