apiVersion: v1
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:log_time}\|%{GREEDYDATA:log_level}\|%{GREEDYDATA:log_app}\|%{GREEDYDATA:log_pid}\|%{GREEDYDATA:log_thread}\|%{GREEDYDATA:log_class}\|%{GREEDYDATA:log_message}"}
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch-master:9200"]
        index => "test-%{+YYYY.MM.dd}"
        user => "elastic"
        password => "iwgame"
      }      
    }
kind: ConfigMap
metadata:
  labels:
    app: logstash-logstash
  name: logstash-logstash-pipeline
  namespace: logging
