apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash-logstash
  name: logstash-logstash-headless
  namespace: logging
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9600
    protocol: TCP
    targetPort: 9600
  selector:
    app: logstash-logstash
